# R Markdown, Bookdown & Blogdown {#rmarkdown}

::: {.infobox .caution data-latex="{caution}"}
**Work In Progress**
:::

## Pourquoi R Markdown ? {#pourquoi-rmarkdown}



R Markdown désigne un format de fichier (à l'extension **.Rmd**) et plus
globalement le framework utilisé pour créer plus facilement des documents
(généralement scientifiques) automatisés. Ces documents peuvent ainsi être
totalement reproductibles et plusieurs formats d'exportation (statiques ou
dynamiques) sont supportés.

Le fichier est écrit via le langage Markdown et des sections de code R peuvent y
être insérées facilement (ainsi que du code écrit via d'autres langages tels
que Python ou SQL). Cela offre une syntaxe facile à lire et à écrire tout en
permettant de générer un document structuré et élégant.

Pour que cela fonctionne, R Markdown est lié à deux packages : `knitr` et le
convertisseur universel de document `pandoc` (Fig. \@ref(fig:rmarkdownflow)).  
Le package `knitr` permet la création, à partir du fichier **.Rmd**, d'un fichier
au format **.md** contenant le code et sa sortie. Ce fichier est alors converti
dans le format d'exportation voulu via `pandoc` (**.html**, **.pdf**, etc).

Pour une configuration plus poussée de la mise en page, selon le format
d'exportation utilisé il est préférable d'avoir quelques bases de HTML/CSS et de
$\LaTeX$. Néanmoins, avec les bons mots-clés il est facile de trouver des
réponses aux problèmes rencontrés via votre moteur de recherche préféré
(généralement, au moins une autre personne s'est arrachée sa belle chevelure sur
un problème similaire au vôtre, s'en est plaint sur un forum équivalent à
[Stackoverflow](https://stackoverflow.com/questions), puis s'est vue
éventuellement répondre un trollesque «
[RTFM](https://knowyourmeme.com/memes/rtfm) »). Néanmoins, la prise en main de
RMarkdown est plutôt facile et sa constante évolution due à sa communauté fait
que la mise en forme des documents est de plus en plus simple.

(ref:rmarkdownflow) Diagramme montrant le processus de création de documents à partir de RMarkdown.

```{r rmarkdownflow, echo=FALSE, fig.cap='(ref:rmarkdownflow)'}
DiagrammeR::mermaid('
  graph LR
    subgraph 
    A[.Rmd] --> B{knitr}
    B --> C(.md)
    end
    subgraph 
    C --> D{pandoc}
    D ==> E((Documents<br>finaux))
    end
', height = '100%', width = '100%')
```

Pour ne pas paraphraser tout l'excellent guide de @rmarkdown2018, je vous invite
à lire leur livre : <https://bookdown.org/yihui/rmarkdown/>, ainsi que leur
nouveau livre [R Markdown
Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/).

***

## Liste de ressources Internet utiles {.unnumbered #ref-rmd}

* R Markdown :
  - [Vue d'ensemble](https://rmarkdown.rstudio.com/lesson-1.html) de R Markdown
  - [Cours](https://ysc-rmarkdown.netlify.app/) sur la communication avec R Markdown
  - [Comment utiliser R Markdown](https://emilyriederer.netlify.app/post/rmarkdown-driven-development/)
  comme base pour le développement de packages bien organisés
  - Quelques [trucs et astuces](https://www.dataquest.io/blog/r-markdown-tips-tricks-and-shortcuts/)
   sur R Markdown
  - [Comment donner du *peps*](https://holtzy.github.io/Pimp-my-rmd/)
   à mon document RMD
  - [Un autre guide](https://www.dataquest.io/blog/r-markdown-guide-cheatsheet/)
   de R Markdown
  - [Guide complet](https://bookdown.org/yihui/rmarkdown/) de R Markdown
  - [Nouveau guide](https://bookdown.org/yihui/rmarkdown-cookbook/)
  de R Markdown (***en cours d'écriture***)
  - [Création d'un template](https://danawanzer.com/using-r-for-immediate-reporting-in-evaluation/)
   R Markdown
* Bookdown :
  - [Site officiel](https://bookdown.org/home/about/) de `bookdown`
  - [Guide complet](https://bookdown.org/yihui/bookdown/) de `bookdown`
  - Extension à `bookdown` : [`bookdownplus`](https://bookdown.org/baydap/bookdownplus/)
  - [Guide en français](https://statistique-et-logiciel-r.com/creer-un-livre-document-avec-bookdown/)
  de `bookdown`
  - [Introduction en français](https://thinkr.fr/rediger-avec-bookdown-pourquoi-comment/)
   à `bookdown`
* Blogdown :
  - [Guide complet](https://bookdown.org/yihui/blogdown/) sur `blogdown`
* Court [tutoriel](https://slides.yihui.org/2017-rmarkdown-UNL-Yihui-Xie.html#1)
 d'introduction sur R Markdown, `bookdown` et `blogdown`
* Guide pour le package [`knitr`](https://yihui.org/knitr/)
* [Options](https://yihui.org/knitr/options/) valables pour les *chunks* de code
et le package `knitr`

***
